version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=fakeimg' >> $BASH_ENV 
            virtualenv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python app/tests.py
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            . venv/bin/activate
            docker build -t rydgel/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push rydgel/$IMAGE_NAME:$TAG
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no root@46.101.160.104 "/bin/bash ./deploy_app.sh rydgel/$IMAGE_NAME:$TAG"
