version: 2
workflows:
  version: 2
  build_all:
    jobs:
      - build
      - test:
          requires:
            - build
  build_master:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
jobs:
  build:
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=fakeimg' >> $BASH_ENV 
            virtualenv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
  test:
    steps:
     - checkout
     - run:
        name: Run Tests
        command: |
          . venv/bin/activate
          python app/tests.py
  deploy:
    docker:
      - image: circleci/python:3.7.8
      - setup_remote_docker:
          docker_layer_caching: true
      - steps:
        - checkout
        - run:
            name: Build and push Docker image
            command: |
              . venv/bin/activate
              docker build -t rydgel/$IMAGE_NAME:$TAG .
              echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
              docker push rydgel/$IMAGE_NAME:$TAG
              docker tag rydgel/$IMAGE_NAME:$TAG rydgel/$IMAGE_NAME:latest
              docker push rydgel/$IMAGE_NAME:latest
        - run:
            name: Deploy app to Digital Ocean Server via Docker
            command: |
              ssh -o StrictHostKeyChecking=no root@46.101.160.104 "/bin/bash ./deploy_app.sh rydgel/$IMAGE_NAME:$TAG"
