version: 2.1
workflows:
  version: 2.1
  build_all:
    jobs:
      - build_and_test
  build_master:
    jobs:
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python app/tests.py
  deploy:
    docker:
      - image: circleci/python:3.7.8
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Variables environment
          command: |
            echo 'export TAG=1.0.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=fakeimg' >> $BASH_ENV 
      - run:
          name: Build and push Docker image
          command: |
            docker build -t rydgel/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push rydgel/$IMAGE_NAME:$TAG
            docker tag rydgel/$IMAGE_NAME:$TAG rydgel/$IMAGE_NAME:latest
            docker push rydgel/$IMAGE_NAME:latest
      - run:
          name: Deploy app to Digital Ocean Server via Docker
          command: |
            ssh -o StrictHostKeyChecking=no root@46.101.160.104 "/bin/bash ./deploy_app.sh rydgel/$IMAGE_NAME:$TAG"
